### PR TITLE
Add html report

### PR DESCRIPTION
**Pull request by kaaax0815**
Now with a good PR. Tested it and it works fine

### CODE REVIEW

**Comment by BetaHuhn** [comment]
Lgtm. Will take a closer look in the evening when I am off school and merge it asap.

**Comment by kaaax0815** [comment]
How is your review going?

**Comment by BetaHuhn** [comment]
Almost done. I decided to move the render function to a separate helper file in order to reuse it for both the email and html command.

**Comment by kaaax0815** [comment]
Yeah makes sense, since its the same code copied

**Comment by kaaax0815** [comment]
Why no gpg key for verified commits?

**Comment by BetaHuhn** [comment]
Now you can see the magic happening 😄

**Comment by BetaHuhn** [comment]
> Why no gpg key for verified commits?

Because I don't think it's necessary for most of my projects. They only prove that the person associated with that gpg key authored the commit, and since I am the only one with write access to my repos I will check what changes make it into the project anyway, so it doesn't make sense for someone to impersonate me.

There are no real drawbacks of signing my commits, but I just haven't had the time (or motivation) to set it up.

**Comment by kaaax0815** [comment]
But e.g. there a Mantainer or Colabs that have right access. and some point in time you make a big project with many issues pr etc and need more people and then you cant do it alone and need to give other people write access.

**Comment by BetaHuhn** [comment]
You are right, I might sign my commits in the future, but right now I can't be bothered to set it up 😄

**Pull request merged**
